# Generated by Django 4.2.7 on 2023-11-15 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('answer_object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='contenttypes.contenttype')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'answer_content_type', 'answer_object_id')},
            },
        ),
        migrations.CreateModel(
            name='VoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('question_object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('author', 'question_content_type', 'question_object_id')},
            },
        ),
        migrations.AlterModelManagers(
            name='answer',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
